/**
 * PDF Generators for all contract templates
 * Each function generates a specific contract type
 */

// Helper functions
const helpers = {
    formatDate: (dateString) => {
        const date = new Date(dateString);
        return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    },
    
    formatCurrency: (amount) => {
        return `$${parseFloat(amount).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
    },
    
    drawHeader: (doc, title, date) => {
        const pageWidth = doc.page.width;
        const margin = 50;
        
        doc.fontSize(32).fillColor('#2563eb')
           .text(title, margin, 60, { align: 'center', width: pageWidth - (margin * 2) });
        
        doc.moveTo(margin, 110).lineTo(pageWidth - margin, 110)
           .strokeColor('#2563eb').lineWidth(2).stroke();
        
        if (date) {
            doc.fontSize(12).fillColor('#64748b')
               .text(`Date: ${helpers.formatDate(date)}`, margin, 130, { align: 'center', width: pageWidth - (margin * 2) });
        }
    },
    
    drawPartyBox: (doc, x, y, width, title, info, color = '#2563eb') => {
        doc.rect(x, y, width, 90).strokeColor(color).lineWidth(1).stroke();
        doc.rect(x, y, width, 25).fillColor(color).fill();
        doc.fontSize(12).fillColor('#ffffff').text(title, x + 10, y + 7);
        doc.fontSize(10).fillColor('#1e293b');
        let yPos = y + 35;
        Object.entries(info).forEach(([key, value]) => {
            if (value) {
                doc.text(`${key}: ${value}`, x + 10, yPos);
                yPos += 15;
            }
        });
    },
    
    addSignatureSection: (doc, party1Name, party2Name) => {
        let yPos = doc.y + 40;
        const margin = 50;
        
        if (yPos > doc.page.height - 250) {
            doc.addPage();
            yPos = 50;
        }
        
        doc.fontSize(16).fillColor('#2563eb').text('SIGNATURES', margin, yPos, { underline: true });
        yPos += 40;
        
        // Party 1 signature
        doc.fontSize(11).fillColor('#1e293b').text('Party 1:', margin, yPos);
        yPos += 20;
        doc.fontSize(10).fillColor('#64748b').text(party1Name, margin, yPos);
        yPos += 30;
        doc.moveTo(margin, yPos).lineTo(margin + 250, yPos).strokeColor('#1e293b').lineWidth(1).stroke();
        yPos += 5;
        doc.fontSize(9).fillColor('#64748b').text('Signature', margin, yPos);
        doc.text('Date: _______________', margin + 300, yPos);
        yPos += 50;
        
        // Party 2 signature
        doc.fontSize(11).fillColor('#1e293b').text('Party 2:', margin, yPos);
        yPos += 20;
        doc.fontSize(10).fillColor('#64748b').text(party2Name, margin, yPos);
        yPos += 30;
        doc.moveTo(margin, yPos).lineTo(margin + 250, yPos).strokeColor('#1e293b').lineWidth(1).stroke();
        yPos += 5;
        doc.fontSize(9).fillColor('#64748b').text('Signature', margin, yPos);
        doc.text('Date: _______________', margin + 300, yPos);
    },
    
    addFooter: (doc) => {
        const footerY = doc.page.height - 40;
        const margin = 50;
        doc.fontSize(8).fillColor('#64748b')
           .text('This document was generated by The Handshake Pro platform. Both parties should retain a signed copy.',
                 margin, footerY, { align: 'center', width: doc.page.width - (margin * 2) });
    }
};

// ========== LOAN AGREEMENT ==========
function generateLoanAgreement(doc, fields) {
    const margin = 50;
    const contentWidth = doc.page.width - (margin * 2);
    
    helpers.drawHeader(doc, 'LOAN AGREEMENT', fields.loanDate);
    
    let yPos = 170;
    
    doc.fontSize(11).fillColor('#1e293b')
       .text('This Loan Agreement is entered into between the parties identified below:',
             margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos += 40;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'LENDER', {
        'Name': fields.lenderName,
        'Email': fields.lenderEmail,
        'Phone': fields.lenderPhone,
        'Address': fields.lenderAddress
    });
    
    yPos += 100;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'BORROWER', {
        'Name': fields.borrowerName,
        'Email': fields.borrowerEmail,
        'Phone': fields.borrowerPhone,
        'Address': fields.borrowerAddress
    });
    
    yPos += 120;
    
    doc.fontSize(16).fillColor('#2563eb').text('LOAN TERMS', margin, yPos, { underline: true });
    yPos += 30;
    
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Principal Amount: ${helpers.formatCurrency(fields.principalAmount)}`, margin, yPos);
    yPos += 20;
    doc.text(`Interest Rate: ${fields.interestRate}% per annum`, margin, yPos);
    yPos += 20;
    doc.text(`Repayment Due Date: ${helpers.formatDate(fields.repaymentDate)}`, margin, yPos);
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Repayment Terms:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.repaymentTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 20;
    
    if (fields.latePaymentPenalty) {
        doc.fontSize(14).fillColor('#2563eb').text('Late Payment Penalty:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b').text(fields.latePaymentPenalty, margin, yPos, { width: contentWidth });
        yPos = doc.y + 20;
    }
    
    if (fields.additionalTerms) {
        doc.fontSize(14).fillColor('#2563eb').text('Additional Terms:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.additionalTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    helpers.addSignatureSection(doc, fields.lenderName, fields.borrowerName);
    helpers.addFooter(doc);
}

// ========== SERVICE AGREEMENT ==========
function generateServiceAgreement(doc, fields) {
    const margin = 50;
    const contentWidth = doc.page.width - (margin * 2);
    
    helpers.drawHeader(doc, 'SERVICE AGREEMENT', fields.startDate);
    
    let yPos = 170;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'SERVICE PROVIDER', {
        'Name/Company': fields.providerName,
        'Email': fields.providerEmail,
        'Phone': fields.providerPhone,
        'Address': fields.providerAddress
    });
    
    yPos += 100;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'CLIENT', {
        'Name/Company': fields.clientName,
        'Email': fields.clientEmail,
        'Phone': fields.clientPhone,
        'Address': fields.clientAddress
    });
    
    yPos += 120;
    
    doc.fontSize(16).fillColor('#2563eb').text('SERVICE DETAILS', margin, yPos, { underline: true });
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Services to be Provided:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.serviceDescription, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 20;
    
    doc.fontSize(14).fillColor('#2563eb').text('Deliverables:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.deliverables, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 20;
    
    doc.fontSize(14).fillColor('#2563eb').text('Timeline:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Start Date: ${helpers.formatDate(fields.startDate)}`, margin, yPos);
    yPos += 15;
    doc.text(`End Date: ${helpers.formatDate(fields.endDate)}`, margin, yPos);
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Payment Terms:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Total Payment: ${helpers.formatCurrency(fields.paymentAmount)}`, margin, yPos);
    yPos += 20;
    doc.text(fields.paymentTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    
    if (fields.additionalTerms) {
        yPos = doc.y + 20;
        doc.fontSize(14).fillColor('#2563eb').text('Additional Terms:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.additionalTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    helpers.addSignatureSection(doc, fields.providerName, fields.clientName);
    helpers.addFooter(doc);
}

// ========== RENTAL AGREEMENT ==========
function generateRentalAgreement(doc, fields) {
    const margin = 50;
    const contentWidth = doc.page.width - (margin * 2);
    
    helpers.drawHeader(doc, 'RENTAL/LEASE AGREEMENT', fields.leaseStartDate);
    
    let yPos = 170;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'LANDLORD', {
        'Name': fields.landlordName,
        'Email': fields.landlordEmail,
        'Phone': fields.landlordPhone,
        'Address': fields.landlordAddress
    });
    
    yPos += 100;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'TENANT', {
        'Name': fields.tenantName,
        'Email': fields.tenantEmail,
        'Phone': fields.tenantPhone
    });
    
    yPos += 110;
    
    doc.fontSize(16).fillColor('#2563eb').text('PROPERTY & LEASE DETAILS', margin, yPos, { underline: true });
    yPos += 30;
    
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Property Address: ${fields.propertyAddress}`, margin, yPos, { width: contentWidth });
    yPos += 20;
    doc.text(`Property Type: ${fields.propertyType}`, margin, yPos);
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Financial Terms:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Monthly Rent: ${helpers.formatCurrency(fields.monthlyRent)}`, margin, yPos);
    yPos += 15;
    doc.text(`Security Deposit: ${helpers.formatCurrency(fields.securityDeposit)}`, margin, yPos);
    yPos += 15;
    doc.text(`Rent Due Date: ${fields.rentDueDate} of each month`, margin, yPos);
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Lease Period:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Start Date: ${helpers.formatDate(fields.leaseStartDate)}`, margin, yPos);
    yPos += 15;
    doc.text(`End Date: ${helpers.formatDate(fields.leaseEndDate)}`, margin, yPos);
    yPos += 30;
    
    if (fields.utilitiesIncluded) {
        doc.fontSize(14).fillColor('#2563eb').text('Utilities Included:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b').text(fields.utilitiesIncluded, margin, yPos, { width: contentWidth });
        yPos = doc.y + 20;
    }
    
    if (fields.additionalTerms) {
        doc.fontSize(14).fillColor('#2563eb').text('Additional Terms:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.additionalTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    helpers.addSignatureSection(doc, fields.landlordName, fields.tenantName);
    helpers.addFooter(doc);
}

// ========== SALES AGREEMENT ==========
function generateSalesAgreement(doc, fields) {
    const margin = 50;
    const contentWidth = doc.page.width - (margin * 2);
    
    helpers.drawHeader(doc, 'SALES AGREEMENT', fields.saleDate);
    
    let yPos = 170;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'SELLER', {
        'Name': fields.sellerName,
        'Email': fields.sellerEmail,
        'Phone': fields.sellerPhone,
        'Address': fields.sellerAddress
    });
    
    yPos += 100;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'BUYER', {
        'Name': fields.buyerName,
        'Email': fields.buyerEmail,
        'Phone': fields.buyerPhone,
        'Address': fields.buyerAddress
    });
    
    yPos += 120;
    
    doc.fontSize(16).fillColor('#2563eb').text('SALE DETAILS', margin, yPos, { underline: true });
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Item/Property Description:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.itemDescription, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Purchase Terms:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Purchase Price: ${helpers.formatCurrency(fields.salePrice)}`, margin, yPos);
    yPos += 15;
    doc.text(`Payment Method: ${fields.paymentMethod}`, margin, yPos);
    yPos += 15;
    doc.text(`Transfer Date: ${helpers.formatDate(fields.transferDate)}`, margin, yPos);
    yPos += 30;
    
    if (fields.warranties) {
        doc.fontSize(14).fillColor('#2563eb').text('Warranties/Guarantees:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.warranties, margin, yPos, { width: contentWidth, align: 'justify' });
        yPos = doc.y + 20;
    }
    
    if (fields.additionalTerms) {
        doc.fontSize(14).fillColor('#2563eb').text('Additional Terms:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.additionalTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    helpers.addSignatureSection(doc, fields.sellerName, fields.buyerName);
    helpers.addFooter(doc);
}

// ========== NDA ==========
function generateNDA(doc, fields) {
    const margin = 50;
    const contentWidth = doc.page.width - (margin * 2);
    
    helpers.drawHeader(doc, 'NON-DISCLOSURE AGREEMENT', fields.effectiveDate);
    
    let yPos = 170;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'DISCLOSING PARTY', {
        'Name/Company': fields.disclosingName,
        'Email': fields.disclosingEmail,
        'Phone': fields.disclosingPhone,
        'Address': fields.disclosingAddress
    });
    
    yPos += 100;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'RECEIVING PARTY', {
        'Name/Company': fields.receivingName,
        'Email': fields.receivingEmail,
        'Phone': fields.receivingPhone,
        'Address': fields.receivingAddress
    });
    
    yPos += 120;
    
    doc.fontSize(16).fillColor('#2563eb').text('CONFIDENTIALITY TERMS', margin, yPos, { underline: true });
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Purpose of Disclosure:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.purpose, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 20;
    
    doc.fontSize(14).fillColor('#2563eb').text('Confidential Information:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.confidentialInfo, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 30;
    
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Duration of Confidentiality: ${fields.duration} years from the effective date`, margin, yPos, { width: contentWidth });
    yPos += 30;
    
    if (fields.exceptions) {
        doc.fontSize(14).fillColor('#2563eb').text('Exceptions to Confidentiality:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.exceptions, margin, yPos, { width: contentWidth, align: 'justify' });
        yPos = doc.y + 20;
    }
    
    if (fields.additionalTerms) {
        doc.fontSize(14).fillColor('#2563eb').text('Additional Terms:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.additionalTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    helpers.addSignatureSection(doc, fields.disclosingName, fields.receivingName);
    helpers.addFooter(doc);
}

// Export all generators (continuing in next part due to length...)
module.exports = {
    loan: generateLoanAgreement,
    service: generateServiceAgreement,
    rental: generateRentalAgreement,
    sales: generateSalesAgreement,
    nda: generateNDA,
    employment: generateEmploymentContract,
    partnership: generatePartnershipAgreement,
    freelance: generateFreelanceContract,
    payment: generatePaymentPlanAgreement,
    consulting: generateConsultingAgreement,
    vehicle: generateVehicleSalesAgreement,
    contractor: generateContractorAgreement,
    roommate: generateRoommateAgreement,
    confidentiality: generateConfidentialityAgreement,
    settlement: generateSettlementAgreement
};

// ========== EMPLOYMENT CONTRACT ==========
function generateEmploymentContract(doc, fields) {
    const margin = 50;
    const contentWidth = doc.page.width - (margin * 2);
    
    helpers.drawHeader(doc, 'EMPLOYMENT CONTRACT', fields.startDate);
    
    let yPos = 170;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'EMPLOYER', {
        'Company': fields.employerName,
        'Email': fields.employerEmail,
        'Phone': fields.employerPhone,
        'Address': fields.employerAddress
    });
    
    yPos += 100;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'EMPLOYEE', {
        'Name': fields.employeeName,
        'Email': fields.employeeEmail,
        'Phone': fields.employeePhone,
        'Address': fields.employeeAddress
    });
    
    yPos += 120;
    
    doc.fontSize(16).fillColor('#2563eb').text('EMPLOYMENT TERMS', margin, yPos, { underline: true });
    yPos += 30;
    
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Position: ${fields.jobTitle}`, margin, yPos);
    yPos += 15;
    if (fields.department) {
        doc.text(`Department: ${fields.department}`, margin, yPos);
        yPos += 15;
    }
    doc.text(`Employment Type: ${fields.employmentType}`, margin, yPos);
    yPos += 15;
    doc.text(`Start Date: ${helpers.formatDate(fields.startDate)}`, margin, yPos);
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Compensation:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Annual Salary: ${helpers.formatCurrency(fields.salary)}`, margin, yPos);
    yPos += 15;
    doc.text(`Payment Schedule: ${fields.paymentSchedule}`, margin, yPos);
    yPos += 30;
    
    if (fields.benefits) {
        doc.fontSize(14).fillColor('#2563eb').text('Benefits:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b').text(fields.benefits, margin, yPos, { width: contentWidth });
        yPos = doc.y + 20;
    }
    
    doc.fontSize(14).fillColor('#2563eb').text('Job Duties & Responsibilities:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.jobDuties, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 20;
    
    doc.fontSize(14).fillColor('#2563eb').text('Work Schedule:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b').text(fields.workSchedule, margin, yPos);
    
    if (fields.additionalTerms) {
        yPos = doc.y + 20;
        doc.fontSize(14).fillColor('#2563eb').text('Additional Terms:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.additionalTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    helpers.addSignatureSection(doc, fields.employerName, fields.employeeName);
    helpers.addFooter(doc);
}

// ========== PARTNERSHIP AGREEMENT ==========
function generatePartnershipAgreement(doc, fields) {
    const margin = 50;
    const contentWidth = doc.page.width - (margin * 2);
    
    helpers.drawHeader(doc, 'PARTNERSHIP AGREEMENT', fields.startDate);
    
    let yPos = 170;
    
    doc.fontSize(14).fillColor('#2563eb').text(`Business Name: ${fields.businessName}`, margin, yPos);
    yPos += 30;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'PARTNER 1', {
        'Name': fields.partner1Name,
        'Email': fields.partner1Email,
        'Phone': fields.partner1Phone,
        'Address': fields.partner1Address,
        'Contribution': helpers.formatCurrency(fields.partner1Contribution),
        'Ownership': `${fields.partner1Ownership}%`
    });
    
    yPos += 120;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'PARTNER 2', {
        'Name': fields.partner2Name,
        'Email': fields.partner2Email,
        'Phone': fields.partner2Phone,
        'Address': fields.partner2Address,
        'Contribution': helpers.formatCurrency(fields.partner2Contribution),
        'Ownership': `${fields.partner2Ownership}%`
    });
    
    yPos += 140;
    
    doc.fontSize(16).fillColor('#2563eb').text('PARTNERSHIP TERMS', margin, yPos, { underline: true });
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Business Purpose:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.businessPurpose, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 20;
    
    doc.fontSize(14).fillColor('#2563eb').text('Profit Distribution:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.profitDistribution, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 20;
    
    doc.fontSize(14).fillColor('#2563eb').text('Decision Making:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.decisionMaking, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 20;
    
    doc.fontSize(14).fillColor('#2563eb').text('Responsibilities:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.responsibilities, margin, yPos, { width: contentWidth, align: 'justify' });
    
    if (fields.additionalTerms) {
        yPos = doc.y + 20;
        doc.fontSize(14).fillColor('#2563eb').text('Additional Terms:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.additionalTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    helpers.addSignatureSection(doc, fields.partner1Name, fields.partner2Name);
    helpers.addFooter(doc);
}

// ========== FREELANCE CONTRACT ==========
function generateFreelanceContract(doc, fields) {
    const margin = 50;
    const contentWidth = doc.page.width - (margin * 2);
    
    helpers.drawHeader(doc, 'FREELANCE CONTRACT', fields.startDate);
    
    let yPos = 170;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'FREELANCER', {
        'Name': fields.freelancerName,
        'Email': fields.freelancerEmail,
        'Phone': fields.freelancerPhone,
        'Address': fields.freelancerAddress
    });
    
    yPos += 100;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'CLIENT', {
        'Name/Company': fields.clientName,
        'Email': fields.clientEmail,
        'Phone': fields.clientPhone,
        'Address': fields.clientAddress
    });
    
    yPos += 120;
    
    doc.fontSize(16).fillColor('#2563eb').text('PROJECT DETAILS', margin, yPos, { underline: true });
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text(`Project Name: ${fields.projectName}`, margin, yPos);
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Project Scope:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.projectScope, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 20;
    
    doc.fontSize(14).fillColor('#2563eb').text('Deliverables:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.deliverables, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Timeline:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Start Date: ${helpers.formatDate(fields.startDate)}`, margin, yPos);
    yPos += 15;
    doc.text(`Deadline: ${helpers.formatDate(fields.deadline)}`, margin, yPos);
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Payment:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Payment Type: ${fields.paymentType}`, margin, yPos);
    yPos += 15;
    doc.text(`Amount: ${helpers.formatCurrency(fields.paymentAmount)}`, margin, yPos);
    yPos += 20;
    doc.text(fields.paymentSchedule, margin, yPos, { width: contentWidth });
    
    if (fields.revisions) {
        yPos = doc.y + 20;
        doc.text(`Revisions Included: ${fields.revisions}`, margin, yPos);
    }
    
    if (fields.additionalTerms) {
        yPos = doc.y + 20;
        doc.fontSize(14).fillColor('#2563eb').text('Additional Terms:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.additionalTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    helpers.addSignatureSection(doc, fields.freelancerName, fields.clientName);
    helpers.addFooter(doc);
}

// ========== PAYMENT PLAN AGREEMENT ==========
function generatePaymentPlanAgreement(doc, fields) {
    const margin = 50;
    const contentWidth = doc.page.width - (margin * 2);
    
    helpers.drawHeader(doc, 'PAYMENT PLAN AGREEMENT', fields.firstPaymentDate);
    
    let yPos = 170;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'CREDITOR', {
        'Name': fields.creditorName,
        'Email': fields.creditorEmail,
        'Phone': fields.creditorPhone,
        'Address': fields.creditorAddress
    });
    
    yPos += 100;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'DEBTOR', {
        'Name': fields.debtorName,
        'Email': fields.debtorEmail,
        'Phone': fields.debtorPhone,
        'Address': fields.debtorAddress
    });
    
    yPos += 120;
    
    doc.fontSize(16).fillColor('#2563eb').text('PAYMENT PLAN DETAILS', margin, yPos, { underline: true });
    yPos += 30;
    
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Total Amount Owed: ${helpers.formatCurrency(fields.totalAmount)}`, margin, yPos);
    yPos += 15;
    if (fields.downPayment && parseFloat(fields.downPayment) > 0) {
        doc.text(`Down Payment: ${helpers.formatCurrency(fields.downPayment)}`, margin, yPos);
        yPos += 15;
    }
    doc.text(`Number of Installments: ${fields.numberOfInstallments}`, margin, yPos);
    yPos += 15;
    doc.text(`Installment Amount: ${helpers.formatCurrency(fields.installmentAmount)}`, margin, yPos);
    yPos += 15;
    doc.text(`Payment Frequency: ${fields.paymentFrequency}`, margin, yPos);
    yPos += 15;
    doc.text(`First Payment Date: ${helpers.formatDate(fields.firstPaymentDate)}`, margin, yPos);
    yPos += 30;
    
    if (fields.interestRate && parseFloat(fields.interestRate) > 0) {
        doc.text(`Interest Rate: ${fields.interestRate}% per annum`, margin, yPos);
        yPos += 15;
    }
    
    if (fields.latePaymentFee && parseFloat(fields.latePaymentFee) > 0) {
        doc.text(`Late Payment Fee: ${helpers.formatCurrency(fields.latePaymentFee)}`, margin, yPos);
        yPos += 15;
    }
    
    doc.text(`Accepted Payment Methods: ${fields.paymentMethod}`, margin, yPos);
    yPos += 30;
    
    if (fields.additionalTerms) {
        doc.fontSize(14).fillColor('#2563eb').text('Additional Terms:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.additionalTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    helpers.addSignatureSection(doc, fields.creditorName, fields.debtorName);
    helpers.addFooter(doc);
}

// ========== CONSULTING AGREEMENT ==========
function generateConsultingAgreement(doc, fields) {
    const margin = 50;
    const contentWidth = doc.page.width - (margin * 2);
    
    helpers.drawHeader(doc, 'CONSULTING AGREEMENT', fields.startDate);
    
    let yPos = 170;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'CONSULTANT', {
        'Name/Firm': fields.consultantName,
        'Email': fields.consultantEmail,
        'Phone': fields.consultantPhone,
        'Address': fields.consultantAddress
    });
    
    yPos += 100;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'CLIENT', {
        'Name/Company': fields.clientName,
        'Email': fields.clientEmail,
        'Phone': fields.clientPhone,
        'Address': fields.clientAddress
    });
    
    yPos += 120;
    
    doc.fontSize(16).fillColor('#2563eb').text('CONSULTING ENGAGEMENT', margin, yPos, { underline: true });
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Scope of Services:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.consultingScope, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 20;
    
    doc.fontSize(14).fillColor('#2563eb').text('Objectives & Goals:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.objectives, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Engagement Period:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Start Date: ${helpers.formatDate(fields.startDate)}`, margin, yPos);
    yPos += 15;
    doc.text(`End Date: ${helpers.formatDate(fields.endDate)}`, margin, yPos);
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Compensation:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Type: ${fields.compensationType}`, margin, yPos);
    yPos += 15;
    doc.text(`Amount: ${helpers.formatCurrency(fields.compensationAmount)}`, margin, yPos);
    yPos += 20;
    doc.text(fields.paymentTerms, margin, yPos, { width: contentWidth });
    
    if (fields.expenseReimbursement) {
        yPos = doc.y + 20;
        doc.fontSize(14).fillColor('#2563eb').text('Expense Reimbursement:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b').text(fields.expenseReimbursement, margin, yPos, { width: contentWidth });
    }
    
    if (fields.additionalTerms) {
        yPos = doc.y + 20;
        doc.fontSize(14).fillColor('#2563eb').text('Additional Terms:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.additionalTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    helpers.addSignatureSection(doc, fields.consultantName, fields.clientName);
    helpers.addFooter(doc);
}

// ========== VEHICLE SALES AGREEMENT ==========
function generateVehicleSalesAgreement(doc, fields) {
    const margin = 50;
    const contentWidth = doc.page.width - (margin * 2);
    
    helpers.drawHeader(doc, 'VEHICLE SALES AGREEMENT', fields.saleDate);
    
    let yPos = 170;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'SELLER', {
        'Name': fields.sellerName,
        'Email': fields.sellerEmail,
        'Phone': fields.sellerPhone,
        'Address': fields.sellerAddress,
        'License': fields.sellerLicense || 'N/A'
    });
    
    yPos += 110;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'BUYER', {
        'Name': fields.buyerName,
        'Email': fields.buyerEmail,
        'Phone': fields.buyerPhone,
        'Address': fields.buyerAddress,
        'License': fields.buyerLicense || 'N/A'
    });
    
    yPos += 130;
    
    doc.fontSize(16).fillColor('#2563eb').text('VEHICLE INFORMATION', margin, yPos, { underline: true });
    yPos += 30;
    
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Year: ${fields.vehicleYear}`, margin, yPos);
    yPos += 15;
    doc.text(`Make: ${fields.vehicleMake}`, margin, yPos);
    yPos += 15;
    doc.text(`Model: ${fields.vehicleModel}`, margin, yPos);
    yPos += 15;
    doc.text(`VIN: ${fields.vehicleVIN}`, margin, yPos);
    yPos += 15;
    doc.text(`Mileage: ${parseFloat(fields.vehicleMileage).toLocaleString()} miles`, margin, yPos);
    yPos += 15;
    doc.text(`Color: ${fields.vehicleColor}`, margin, yPos);
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Vehicle Condition:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.vehicleCondition, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Sale Terms:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Sale Price: ${helpers.formatCurrency(fields.salePrice)}`, margin, yPos);
    yPos += 15;
    doc.text(`Payment Method: ${fields.paymentMethod}`, margin, yPos);
    yPos += 30;
    
    if (fields.warranty) {
        doc.fontSize(14).fillColor('#2563eb').text('Warranty:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b').text(fields.warranty, margin, yPos, { width: contentWidth });
        yPos = doc.y + 20;
    }
    
    if (fields.additionalTerms) {
        doc.fontSize(14).fillColor('#2563eb').text('Additional Terms:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.additionalTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    helpers.addSignatureSection(doc, fields.sellerName, fields.buyerName);
    helpers.addFooter(doc);
}

// ========== CONTRACTOR AGREEMENT ==========
function generateContractorAgreement(doc, fields) {
    const margin = 50;
    const contentWidth = doc.page.width - (margin * 2);
    
    helpers.drawHeader(doc, 'CONTRACTOR AGREEMENT', fields.startDate);
    
    let yPos = 170;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'CONTRACTOR', {
        'Name/Company': fields.contractorName,
        'Email': fields.contractorEmail,
        'Phone': fields.contractorPhone,
        'Address': fields.contractorAddress,
        'License': fields.contractorLicense || 'N/A'
    });
    
    yPos += 110;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'PROPERTY OWNER', {
        'Name': fields.ownerName,
        'Email': fields.ownerEmail,
        'Phone': fields.ownerPhone,
        'Property Address': fields.propertyAddress
    });
    
    yPos += 130;
    
    doc.fontSize(16).fillColor('#2563eb').text('PROJECT DETAILS', margin, yPos, { underline: true });
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Work to be Performed:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.projectDescription, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 20;
    
    doc.fontSize(14).fillColor('#2563eb').text('Materials & Equipment:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.materials, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Timeline & Payment:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Start Date: ${helpers.formatDate(fields.startDate)}`, margin, yPos);
    yPos += 15;
    doc.text(`Completion Date: ${helpers.formatDate(fields.completionDate)}`, margin, yPos);
    yPos += 15;
    doc.text(`Total Cost: ${helpers.formatCurrency(fields.totalCost)}`, margin, yPos);
    yPos += 20;
    doc.text(fields.paymentSchedule, margin, yPos, { width: contentWidth });
    
    if (fields.permits) {
        yPos = doc.y + 20;
        doc.fontSize(14).fillColor('#2563eb').text('Permits & Inspections:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b').text(fields.permits, margin, yPos, { width: contentWidth });
    }
    
    if (fields.insurance) {
        yPos = doc.y + 20;
        doc.fontSize(14).fillColor('#2563eb').text('Insurance & Liability:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b').text(fields.insurance, margin, yPos, { width: contentWidth });
    }
    
    if (fields.additionalTerms) {
        yPos = doc.y + 20;
        doc.fontSize(14).fillColor('#2563eb').text('Additional Terms:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.additionalTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    helpers.addSignatureSection(doc, fields.contractorName, fields.ownerName);
    helpers.addFooter(doc);
}

// ========== ROOMMATE AGREEMENT ==========
function generateRoommateAgreement(doc, fields) {
    const margin = 50;
    const contentWidth = doc.page.width - (margin * 2);
    
    helpers.drawHeader(doc, 'ROOMMATE AGREEMENT', fields.leaseStartDate);
    
    let yPos = 170;
    
    doc.fontSize(14).fillColor('#2563eb').text(`Property: ${fields.propertyAddress}`, margin, yPos, { width: contentWidth });
    yPos += 30;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'ROOMMATE 1', {
        'Name': fields.roommate1Name,
        'Email': fields.roommate1Email,
        'Phone': fields.roommate1Phone,
        'Rent Share': helpers.formatCurrency(fields.roommate1RentShare)
    });
    
    yPos += 110;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'ROOMMATE 2', {
        'Name': fields.roommate2Name,
        'Email': fields.roommate2Email,
        'Phone': fields.roommate2Phone,
        'Rent Share': helpers.formatCurrency(fields.roommate2RentShare)
    });
    
    yPos += 130;
    
    doc.fontSize(16).fillColor('#2563eb').text('LIVING ARRANGEMENT', margin, yPos, { underline: true });
    yPos += 30;
    
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Agreement Period: ${helpers.formatDate(fields.leaseStartDate)} to ${helpers.formatDate(fields.leaseEndDate)}`, margin, yPos, { width: contentWidth });
    yPos += 15;
    doc.text(`Total Monthly Rent: ${helpers.formatCurrency(fields.totalRent)}`, margin, yPos);
    yPos += 15;
    doc.text(`Security Deposit: ${helpers.formatCurrency(fields.securityDeposit)}`, margin, yPos);
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Utilities:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.utilitiesSplit, margin, yPos, { width: contentWidth });
    
    yPos = doc.y + 20;
    
    doc.fontSize(14).fillColor('#2563eb').text('Shared & Private Spaces:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.sharedSpaces, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 20;
    
    doc.fontSize(14).fillColor('#2563eb').text('House Rules:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.houseRules, margin, yPos, { width: contentWidth, align: 'justify' });
    
    if (fields.additionalTerms) {
        yPos = doc.y + 20;
        doc.fontSize(14).fillColor('#2563eb').text('Additional Terms:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.additionalTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    helpers.addSignatureSection(doc, fields.roommate1Name, fields.roommate2Name);
    helpers.addFooter(doc);
}

// ========== CONFIDENTIALITY AGREEMENT ==========
function generateConfidentialityAgreement(doc, fields) {
    const margin = 50;
    const contentWidth = doc.page.width - (margin * 2);
    
    helpers.drawHeader(doc, 'CONFIDENTIALITY AGREEMENT', fields.effectiveDate);
    
    let yPos = 170;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'FIRST PARTY', {
        'Name/Company': fields.party1Name,
        'Email': fields.party1Email,
        'Phone': fields.party1Phone,
        'Address': fields.party1Address
    });
    
    yPos += 100;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'SECOND PARTY', {
        'Name/Company': fields.party2Name,
        'Email': fields.party2Email,
        'Phone': fields.party2Phone,
        'Address': fields.party2Address
    });
    
    yPos += 120;
    
    doc.fontSize(16).fillColor('#2563eb').text('CONFIDENTIALITY TERMS', margin, yPos, { underline: true });
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Subject Matter:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.confidentialMatter, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 20;
    
    doc.fontSize(14).fillColor('#2563eb').text('Protected Information:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.protectedInfo, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 30;
    
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Duration: ${fields.duration} years from the effective date`, margin, yPos);
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Obligations:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.obligations, margin, yPos, { width: contentWidth, align: 'justify' });
    
    if (fields.permittedDisclosures) {
        yPos = doc.y + 20;
        doc.fontSize(14).fillColor('#2563eb').text('Permitted Disclosures:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.permittedDisclosures, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    if (fields.additionalTerms) {
        yPos = doc.y + 20;
        doc.fontSize(14).fillColor('#2563eb').text('Additional Terms:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.additionalTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    helpers.addSignatureSection(doc, fields.party1Name, fields.party2Name);
    helpers.addFooter(doc);
}

// ========== SETTLEMENT AGREEMENT ==========
function generateSettlementAgreement(doc, fields) {
    const margin = 50;
    const contentWidth = doc.page.width - (margin * 2);
    
    helpers.drawHeader(doc, 'SETTLEMENT AGREEMENT', fields.settlementDate);
    
    let yPos = 170;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'FIRST PARTY', {
        'Name': fields.party1Name,
        'Email': fields.party1Email,
        'Phone': fields.party1Phone,
        'Address': fields.party1Address
    });
    
    yPos += 100;
    
    helpers.drawPartyBox(doc, margin, yPos, contentWidth, 'SECOND PARTY', {
        'Name': fields.party2Name,
        'Email': fields.party2Email,
        'Phone': fields.party2Phone,
        'Address': fields.party2Address
    });
    
    yPos += 120;
    
    doc.fontSize(16).fillColor('#2563eb').text('SETTLEMENT TERMS', margin, yPos, { underline: true });
    yPos += 30;
    
    doc.fontSize(14).fillColor('#2563eb').text('Dispute Description:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.disputeDescription, margin, yPos, { width: contentWidth, align: 'justify' });
    
    yPos = doc.y + 30;
    
    if (fields.settlementAmount && parseFloat(fields.settlementAmount) > 0) {
        doc.fontSize(14).fillColor('#2563eb').text('Settlement Amount:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b');
        doc.text(helpers.formatCurrency(fields.settlementAmount), margin, yPos);
        yPos += 30;
    }
    
    doc.fontSize(14).fillColor('#2563eb').text('Terms of Settlement:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.settlementTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    
    if (fields.paymentSchedule) {
        yPos = doc.y + 20;
        doc.fontSize(14).fillColor('#2563eb').text('Payment Schedule:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.paymentSchedule, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    yPos = doc.y + 20;
    
    doc.fontSize(14).fillColor('#2563eb').text('Release of Claims:', margin, yPos);
    yPos += 20;
    doc.fontSize(11).fillColor('#1e293b')
       .text(fields.releaseOfClaims, margin, yPos, { width: contentWidth, align: 'justify' });
    
    if (fields.confidentiality) {
        yPos = doc.y + 20;
        doc.fontSize(14).fillColor('#2563eb').text('Confidentiality:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.confidentiality, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    if (fields.additionalTerms) {
        yPos = doc.y + 20;
        doc.fontSize(14).fillColor('#2563eb').text('Additional Terms:', margin, yPos);
        yPos += 20;
        doc.fontSize(11).fillColor('#1e293b')
           .text(fields.additionalTerms, margin, yPos, { width: contentWidth, align: 'justify' });
    }
    
    helpers.addSignatureSection(doc, fields.party1Name, fields.party2Name);
    helpers.addFooter(doc);
}
